trigger:
- main
- pipeline_debug

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'WebViewSDK.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
    args: 'CONFIGURATION_BUILD_DIR=$(Build.BinariesDirectory)/build_output'

- script: |
    # ls -lFht ./**
    # ls -lFht ./build/**
    # ls -lFht ./WebViewSDK.xcodeproj/**
    find ~/Library/Developer/Xcode/DerivedData/WebViewSDK* -iname "WebViewSDK.framework"
    ls -lFht $(Build.BinariesDirectory)/build_output/**
