trigger:
  batch: true
  branches:
    include:
    - main
    # - develop
    # - testing
    # - staging
    - pipeline_debug

variables:
  vmImageMac: 'macos-latest'
  vmImageUbu: 'ubuntu-latest'
  tplProjectName: 'ios-webview-sdk'
  # ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  #   webAppName: prod-dxp
  #   cdnAccountName: proddxpcdn
  #   cdnGroup: prod-dxp-grp
  #   cdnEndpoint: prod-dxp
  #   domainDXP: tldxp.com
  #   saveLast: 10
  #   uriPath: 'webview-sdk/android''
  #   performPurgeCDN: true
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    webAppName: dev-dxp
    cdnAccountName: devdxpcdn
    cdnGroup: dev-dxp-grp
    cdnEndpoint: dev-dxp
    domainDXP: developdxp.com
    saveLast: 10
    uriPath: 'webview-sdk/android'
    performPurgeAFD: true
  ${{ elseif eq(variables['Build.SourceBranchName'], 'pipeline_debug') }}:
    webAppName: dev-dxp
    cdnAccountName: devdxpcdn
    cdnGroup: dev-dxp-grp
    cdnEndpoint: dev-dxp
    domainDXP: developdxp.com
    saveLast: 10
    uriPath: 'webview-sdk/android'
    performPurgeAFD: true
  # ${{ elseif eq(variables['Build.SourceBranchName'], 'testing') }}:
  #   webAppName: test-dxp
  #   cdnAccountName: testdxpcdn
  #   cdnGroup: test-dxp-grp
  #   cdnEndpoint: test-dxp
  #   domainDXP: testingdxp.com
  #   saveLast: 10
  #   uriPath: 'webview-sdk/android'
  #   # temporary var performPurgeAFD
  #   performPurgeAFD: true
  # ${{ elseif eq(variables['Build.SourceBranchName'], 'staging') }}:
  #   webAppName: stag-dxp
  #   cdnAccountName: stagdxpcdn
  #   cdnGroup: stag-dxp-grp
  #   cdnEndpoint: stag-dxp
  #   domainDXP: stagingdxp.com
  #   saveLast: 10
  #   uriPath: 'webview-sdk/android'
  #   performPurgeCDN: true
  ${{ elseif eq(variables['Build.Reason'], 'PullRequest') }}:
    cdnAccountName: devdxpcdn
    cdnGroup: dev-dxp-grp
    cdnEndpoint: dev-dxp
    domainDXP: developdxp.com
    saveLast: 10
    uriPath: 'webview-sdk/android'

parameters:
- name: cdnAccountName
  displayName: cdnAccountName
  type: string
  default: $(cdnAccountName)
- name: cdnGroup
  displayName: cdnGroup
  type: string
  default: $(cdnGroup)
- name: cdnEndpoint
  displayName: cdnEndpoint
  type: string
  default: $(cdnEndpoint)
- name: domainDXP
  displayName: domainDXP
  type: string
  default: $(domainDXP)
- name: deleteOlderCDN
  displayName: deleteOlderCDN
  type: string
  default: $(deleteOlderCDN)
- name: uriPath
  displayName: uriPath
  type: string
  default: $(uriPath)
- name: X_API
  displayName: X_API
  type: string
  default: undefined
- name: webAppName
  type: string
  default: $(webAppName)
- name: customPerformPurgeAFD
  type: boolean
  default: false

stages:
  - stage: build
    displayName: Build stage
    pool:
      vmImage: $(vmImageMac)
    jobs:
      - job: BuildAndPublish
        steps:

          - task: Xcode@5
            displayName: 'Build with Xcode'
            inputs:
              actions: 'build'
              scheme: ''
              sdk: 'iphoneos'
              configuration: 'Release'
              xcWorkspacePath: 'WebViewSDK.xcodeproj/project.xcworkspace'
              xcodeVersion: 'default'
              args: 'CONFIGURATION_BUILD_DIR=$(Build.BinariesDirectory)/build_output'

          - script: ls -lFht $(Build.BinariesDirectory)/build_output
            displayName: 'show the contents of $(Build.BinariesDirectory)/build_output'

          - task: ArchiveFiles@2
            displayName: 'Archive WebViewSDK.framework'
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            inputs:
              rootFolderOrFile: $(Build.BinariesDirectory)/build_output/WebViewSDK.framework
              includeRootFolder: true #false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/WebViewSDK.framework.b$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/WebViewSDK.framework.b$(Build.BuildId).zip
            artifact: drop
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: Deploy
        displayName: Deploy stage
        environment: ${{parameters.cdnAccountName}}

        pool:
          vmImage: $(vmImageUbu)
        strategy:
          runOnce:
            deploy:
              steps:

                - bash: |
                    echo ${{ parameters.cdnAccountName }}
                    echo ${{ parameters.cdnGroup }}
                    echo ${{ parameters.cdnEndpoint }}
                    echo ${{ parameters.domainDXP }}
                    echo ${{ parameters.deleteOlderCDN }}
                    echo ${{ parameters.uriPath }}
                  displayName: Show Parameters Value

                - task: ExtractFiles@1
                  displayName: 'Extract ${{ variables.tplProjectName }} ${{ parameters.cdnAccountName }}'
                  inputs:
                    destinationFolder: ./${{ variables.tplProjectName }}
                    archiveFilePatterns: $(Pipeline.Workspace)/drop/WebViewSDK.framework.b$(Build.BuildId).zip
                    cleanDestinationFolder: true
                    overwriteExistingFiles: false
                
                - script: ls -lFht ./${{ variables.tplProjectName }}
